vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /assets/uploaded_images
            upload_destination: '%kernel.project_dir%/public/assets/uploaded_images'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
