<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYqjkV9J\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYqjkV9J/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYqjkV9J.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYqjkV9J\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYqjkV9J\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YqjkV9J',
    'container.build_id' => '866f68e2',
    'container.build_time' => 1579251156,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYqjkV9J');
