<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO27kahp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO27kahp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO27kahp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO27kahp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerO27kahp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'O27kahp',
    'container.build_id' => 'c186e723',
    'container.build_time' => 1579218415,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO27kahp');
